### ISSUE TITLE
El id es autogenerado

### ISSUE THREAD

**Issue by CRAG666** [cgr97/-CesarGarciaRamirez-_objeto_seguro#1]
Si nos vamos al documento en este se mensiona que el minimo registro del diccionario es el ID, este id es autogenerado por ti, a si como a criterio tambien queda otros campos que quieras agregar, por otro lado debes leer la descripcion de consultar_msj pues en ella se describen otros argumentos a tener dentro de la estructura de tu diccionario.

> Nota: el ID y el mensaje es la mínima información que deberá tener el registro, el alumno puede asignar más campos de acuerdo con su criterio. 

Cabe aclarar que para que tu puedas consultar primero tienes que almacenar esos diccionarios en alguna estructura que desees y sea la mas adecuada para esta tarea

**Comment by CRAG666** [comment]
@cgr97 Puedes responder si tienes alguna otra cuestion relacionada y si esto fue de ayuda y soluciono tu duda por favor cierra la issue

**Comment by cgr97** [comment]
Si profe gracias, si me ayudo y de hecho creo que ya lo logré, todos mis metodos funcionan correctamente, ahora tengo otra duda: en el pdf dice que el metodo de esperar_respuesta tiene que ser llamado automaticamente siempre que se recibe un saludo, sin embargo, no supe como llamar a un método y dejarlo esperando a recibir un mensaje. ¿podria orientarme un poco?

**Comment by CRAG666** [comment]
le respondi lo mismo a tu compañera fabor de leer https://github.com/nayaxolotl/Nayeli_Gissel_Larios_Perez_objeto_seguro/issues/1

**Comment by CRAG666** [comment]
Si a caso continuan escribe nuevamente en tu README las nuevas preguntas

**Comment by CRAG666** [comment]
recuerda que si quieres avisarme de nuevos mensajes arrobame a si como yo lo hice @cgr97

**Comment by cgr97** [comment]
@CRAG666 Gracias, de hecho es masomenos parecido a lo que yo habia hecho, lo que me confundía era que decia que esperar respuesta se activaba automaticamente, pero si se puede llamar despues de saludar entonces eso es lo que hice. Ya por último, yo agregué un nuevo metodo llamado "intercambio" para que ambos objetos seguros puedan guardar la llave publica y nombre del otro y manejen las llaves publicas para cifrar automaticamente. ¿Hay problema con eso de haber agregado un nuevo método?

**Comment by CRAG666** [comment]
Claro que no recuerda que la descripcion son solo los requerimientos minimos lo demas quede de ti saludos @cgr97 cerrrare la issue y abreo otra si tienes dudas todavia

**Comment by cgr97** [comment]
@CRAG666 Gracias, de hecho es masomenos parecido a lo que yo habia hecho, lo que me confundía era que decia que esperar respuesta se activaba automaticamente, pero si se puede llamar despues de saludar entonces eso es lo que hice. Ya por último, yo agregué un nuevo metodo llamado "intercambio" para que ambos objetos seguros puedan guardar la llave publica y nombre del otro y manejen las llaves publicas para cifrar automaticamente. ¿Hay problema con eso de haber agregado un nuevo método?
